### ISSUE TITLE
[Question] Salt-cloud plugin support 

### ISSUE THREAD

**Issue by pieterbork** [vultr/vultr-cli#107]
Hello!

Posting here because I didn't know the right place for a question like this - I didn't quite get the response I was looking for by opening a support ticket.

I'm a new Vultr user and it's great to see you guys active in the Open source space. I use salt-cloud to manage all of my VMs which currently uses this plugin https://github.com/saltstack/salt/blob/master/salt/cloud/clouds/vultrpy.py to interact with vultr. This plugin is less feature rich than some of the plugins for other providers like DO, and I was wondering if there is a chance you guys would consider checking it out/supporting it. It's currently missing features like adding ssh keys, working with bare metal, etc - it would be nice to see this migrated over to the v2 API once that is released into production as well.

Thanks for all your hard work, loving vultr so far!

Cheers,
Pieter

**Comment by ddymko** [comment]
Hey @pieterbork 

Thanks for reaching out! I wouldn't mind checking out the plugin that you mentioned however given the workload that we have with API v2 (and porting our official tooling to API v2) this may not be something that we may get around to officially supporting or porting to v2 immediately. 

I do urge and welcome the community to contribute on our official repos and ones like the salt stack.
