### ISSUE TITLE
[BUG] - Can't list domain with more than 20 records

### ISSUE THREAD

**Issue by jdmulloy** [vultr/vultr-cli#122]
**Describe the bug**
The DNS v2 API is paginated and the cli seems to not have a way to handle this, so domains with more than 20 records will only show the first 20 records. It does print out the "next page" cursor key but there doesn't seem to be any way to use it.

**To Reproduce**
1. Have a domain with more than 20 records
2. Run `vultr-cli dns record list example.com`
3. See that only 20 records are show and the output ends with ```======================================
TOTAL	NEXT PAGE		PREV PAGE
27	bmV4dF9fMjA1NTcwODQ=```

**Expected behavior**
Full list of domain records is printed or there is a CLI option to feed in the next page cursor

**Comment by ddymko** [comment]
@jdmulloy we'll get this patched up and released
