### ISSUE TITLE
[Feature] - documentation-request for setting .vultr-cli.yaml configuration file

### ISSUE THREAD

**Issue by ryan-c-dev** [vultr/vultr-cli#147]
I'm not sure how to properly format the yaml config file. An example config file would be really nice.

Also if I want to deploy a server instance, I can't seem to see an option for a Cloud Compute instance (new jersey, cheapest option w/ ipv4!)

when running: **vultr-cli plans list** I get a list but it's outputting NEXT PAGE PREV PAGE to my terminal which I can't really use. 

Attached a photo of my output, would be cool to learn your API more!

![pic-full-210424-0125-18](https://user-images.githubusercontent.com/50060288/115952582-96186780-a49b-11eb-8a18-25617d03bfbb.png)

**Comment by ddymko** [comment]
@ryan-c-dev 

We'll update the readme to add in an example for the yaml config. Right now it's pretty bare bones as it only has 1 available field to work with

```sh
cat ~/.vultr-cli.yaml
api-key:
```

For `vultr-cli plans list` the fields you see `Total, Next Page, Prev Page` are the pagination fields. So with any list call you can configure how many items you want returned

```
  -c, --cursor string   (optional) Cursor for paging.
  -h, --help            help for list
  -p, --per-page int    (optional) Number of items requested per page. Default is 100 and Max is 500. (default 100)
  ```

So if I want to return a single plan the command would be 

```sh
RICE PER MONTH		TYPE	REGIONS
vc2-1c-1gb	1		1024	25	1		1024		5vc2	[ewr ord dfw sea lax atl ams lhr fra sjc syd yto cdg nrt icn mia sgp]
======================================
TOTAL	NEXT PAGE			PREV PAGE
21	bmV4dF9fdmMyLTFjLTFnYg==
```

With the next page being the string to pass in to the `-c, --cursor` flag

As for the cheapest plans the $2.5 and $3.5 plans are not available through the API. The cheapest plan available through the API starts at $5

**Comment by ryan-c-dev** [comment]
Hey thanks a lot, keep up the great work!

**Comment by ddymko** [comment]
https://github.com/vultr/vultr-cli/blob/master/README.md#example-vultr-cliyaml-config-file
