### ISSUE TITLE
[Feature] Shell Completion Subcommand

### ISSUE THREAD

**Issue by shaneutt** [vultr/vultr-cli#167]
**Is your feature request related to a problem? Please describe.**

I would like to be able to use a sub-command to configure shell completion for `vultr-cli`, having support for `bash` at minimum.

**Describe the solution you'd like**

```shell
$ source <(vultr-cli completion bash)
```

**Comment by shaneutt** [comment]
Just noticed this is a duplicate: https://github.com/vultr/vultr-cli/issues/92

**Comment by ddymko** [comment]
@shaneutt With the latest release 2.6.0 shell completions were added in just not documented yet (I'll add this to the readme this week)

I added an overview to #92
