### ISSUE TITLE
[Feature] - Vutlr kubernetes engine enablement

### ISSUE THREAD

**Issue by curx** [vultr/vultr-cli#175]
Is the Vultr Kubernetes Engine (VKE) enabled with the cli?

**Comment by ddymko** [comment]
@curx 

Not at the moment. I have a PR that adds VKE support to the base go plugin that the CLI uses. Once that gets merged in we'll work on adding support to the CLI.

**Comment by ddymko** [comment]
@curx VKE supported was release in v2.8.0 of the CLI
