### ISSUE TITLE
[Feature] - Custom ISO workflow?

### ISSUE THREAD

**Issue by jakimfett** [vultr/vultr-cli#206]
Unsure if this exists (and I'm missing the functionality somewhere) or if it's actually a feature request.

I'd like to use the Vultr CLI tool to deploy instances based on an ISO at a remote URL.

At the moment, I've manually uploaded my ISO via the webUI, but am not seeing a way to select the specific system image within the `vultr-cli instance create` syntax.

Would prefer to avoid the webui completely, any suggestions? Is this currently possible?

**Comment by ddymko** [comment]
@jakimfett 

For ISOs once uploaded you them you have to get the ISOs ID and you can use pass that to the instance create call

```
      --iso string              iso ID you want to create the instance with
```

As for remote booting instance create also supports iPXE

```
     --ipxe string             if you've selected the 'custom' operating system, this can be set to chainload the specified URL on bootup
 ```

**Comment by jakimfett** [comment]
@ddymko thank you, appreciate your time!
