### ISSUE TITLE
[Feature] - Add transparent pagination support for long results

### ISSUE THREAD

**Issue by radonm** [vultr/vultr-cli#233]
Currently long results returned by the client are split in pages and the user has to request multiple pages using the pointers at the end of each page. This behavior makes it difficult for script automation. It would be helpful to have a new switch which would make vultr-cli handle pagination transparently for the user a return a single data set.

**Comment by optik-aper** [comment]
@radonm This is a function of how the API returns results and isn't something we necessarily want to behave differently in the CLI.  If you use the `--per-page` flags you can increase the number of results returned up to 500 which is limited by the API itself.

Additionally, if you want a different option for scripting, you'd probably be better served by the [govultr](https://github.com/vultr/govultr), [vultr-php](https://github.com/vultr/vultr-php) or [vultr-node](https://github.com/vultr/vultr-node) packages which wrap the calls to the API.
