### ISSUE TITLE
[Feature] - Add Vultr CLI to scoop package manager for developers using Windows 11

### ISSUE THREAD

**Issue by pcgeek86** [vultr/vultr-cli#237]
**Is your feature request related to a problem? Please describe.**

- I use Windows 11 on my developer workstation.
- I use the Scoop package manager to install and update various GUI and CLI development tools, such as Visual Studio Code and Node.js.
- I would like to install the Vultr CLI tool using the same package manager as my other development tools.

**Describe the solution you'd like**

Add Vultr CLI as a Scoop package, by creating a manifest for it.

https://scoop-docs.vercel.app/docs/concepts/App-Manifests.html

Many example manifests can be found in the `main` bucket for Scoop.

https://github.com/ScoopInstaller/Main/tree/master/bucket

**Comment by ddymko** [comment]
@pcgeek86 Thanks for the request.

We can look into getting vultr-cli into scoop or if you are interested in submitting the changes for scoop yourself that would also be great!

**Comment by pcgeek86** [comment]
Submitted PR https://github.com/ScoopInstaller/Main/pull/3394

**Comment by ddymko** [comment]
looks like this was merged into master closing ticket
