### ISSUE TITLE
[BUG] - Unable to create an instance from snapshot

### ISSUE THREAD

**Issue by rohankrishnadev** [vultr/vultr-cli#256]
**Describe the bug**
When trying to create an instance from snapshot, I get `unknown flag: --snapshot_id` error.

**To Reproduce**
1. Create a snapshot of an existing instance `vultr-cli snapshot create --id $UUID_INSTANCE --description vulture-snapshot`
2. Delete instance `vultr-cli instance delete $UUID_INSTANCE`
3. Create new instance from snapshot `vultr-cli instance create --region $REGION --plan $PLAN_ID --snapshot_id $UUID_SNAPSHOT`
4. See error `unknown flag: --snapshot_id`

**Expected behavior**
A new instance is created from the snapshot

**Screenshots**
N/A

**Desktop (please complete the following information where applicable:**
 - OS: macOS Monterey
 - Version: Vultr-cli v2.13.0 (installed via Homebrew)

**Additional context**
N/A

**Comment by ddymko** [comment]
@rohankrishnadev Looks like the example that is in the codebase has typo as it should be `snapshot` not `snapshot_id`.

```sh
☁  ~  vultr-cli instance create -h | grep snapshot
Create a new instance with specified plan, region and os (from image, snapshot, app or ISO)

      --snapshot string         snapshot ID you want to create the instance with
 ```
 
 We will review and clean this up

**Comment by ddymko** [comment]
The verbiage changes will be reflected in the next release
