### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tianon** [vultr/vultr-cli#27]
(Thanks for creating this!! :+1:)

I've got an API key that I've been using via `curl` to do API requests previously, and I figured I should give this new tool a shot but no matter what command I attempt, I get a segfault:

```console
$ vultr-cli server list
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x72f44e]

goroutine 1 [running]:
github.com/vultr/govultr.(*Client).DoWithContext(0xc0000b9040, 0x9f56c0, 0xc0000aa018, 0xc000133f00, 0x881c00, 0xc0000ae3b0, 0x0, 0x0)
	/Users/ddymko/go/pkg/mod/github.com/vultr/govultr@v0.1.3/govultr.go:169 +0x12e
github.com/vultr/govultr.(*ServerServiceHandler).list(0xc0000ae380, 0x9f56c0, 0xc0000aa018, 0x0, 0x0, 0x0, 0x0, 0x2, 0x2, 0x1, ...)
	/Users/ddymko/go/pkg/mod/github.com/vultr/govultr@v0.1.3/server.go:1431 +0x127
github.com/vultr/govultr.(*ServerServiceHandler).List(0xc0000ae380, 0x9f56c0, 0xc0000aa018, 0xc0000240c5, 0x542b74, 0xc000133d00, 0x939a0c, 0x4)
	/Users/ddymko/go/pkg/mod/github.com/vultr/govultr@v0.1.3/server.go:1395 +0x53
github.com/vultr/vultr-cli/cmd.glob..func135(0xd3d1c0, 0xd68698, 0x0, 0x0)
	/Users/ddymko/go/src/github.com/vultr/vultr-cli/cmd/server.go:438 +0x5f
github.com/spf13/cobra.(*Command).execute(0xd3d1c0, 0xd68698, 0x0, 0x0, 0xd3d1c0, 0xd68698)
	/Users/ddymko/go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xd3ae20, 0x2, 0x2, 0xc0000ba500)
	/Users/ddymko/go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:850 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/ddymko/go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:800
github.com/vultr/vultr-cli/cmd.Execute()
	/Users/ddymko/go/src/github.com/vultr/vultr-cli/cmd/root.go:41 +0x32
main.main()
	/Users/ddymko/go/src/github.com/vultr/vultr-cli/main.go:20 +0x20
```

```console
$ vultr-cli api-key
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x72f44e]

goroutine 1 [running]:
github.com/vultr/govultr.(*Client).DoWithContext(0xc0000b71e0, 0x9f56c0, 0xc0000a8018, 0xc000131c00, 0x87c400, 0xc0000cab80, 0x0, 0x0)
	/Users/ddymko/go/pkg/mod/github.com/vultr/govultr@v0.1.3/govultr.go:169 +0x12e
github.com/vultr/govultr.(*APIServiceHandler).GetInfo(0xc0000ac300, 0x9f56c0, 0xc0000a8018, 0xc000131a00, 0x939a0c, 0x4)
	/Users/ddymko/go/pkg/mod/github.com/vultr/govultr@v0.1.3/api.go:37 +0xfc
github.com/vultr/vultr-cli/cmd.glob..func2(0xd42c00, 0xd68698, 0x0, 0x0)
	/Users/ddymko/go/src/github.com/vultr/vultr-cli/cmd/apiKey.go:35 +0x53
github.com/spf13/cobra.(*Command).execute(0xd42c00, 0xd68698, 0x0, 0x0, 0xd42c00, 0xd68698)
	/Users/ddymko/go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xd3ae20, 0x2, 0x2, 0xc0000b8500)
	/Users/ddymko/go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:850 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/ddymko/go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:800
github.com/vultr/vultr-cli/cmd.Execute()
	/Users/ddymko/go/src/github.com/vultr/vultr-cli/cmd/root.go:41 +0x32
main.main()
	/Users/ddymko/go/src/github.com/vultr/vultr-cli/main.go:20 +0x20
```

Do I need to create a new API key or create it differently for this tool?

(FWIW, I'm using the `vultr-cli_linux_amd64.tar.gz` binary attached to https://github.com/vultr/vultr-cli/releases/tag/v0.1.0 currently, but I'm happy to build from source instead if that would be helpful. :+1:)

**Comment by ddymko** [comment]
Hey there @tianon !

You can use your existing API key with no problems.

I just pulled down the the mac binary (vultr-cli_darwin_amd64.tar.gz). This binary was working fine...I also renamed it to vultr-cli (I noticed you were calling executing the binary as `vultr-cli`) and this was also working fine. 

Not sure what the issue might be - I am going to double check to make sure that the linux binaries are running fine. I would recommend to see if you can build from source and have that binary run for you while I look into the linux binaries.

Also what version of Go are you running on your machine?

**Comment by ddymko** [comment]
@tianon 

Just tried running the `vultr-cli_linux_amd64.tar.gz` on Ubuntu 18.04 and it was able to run just fine.

Could you share what Linux distro and version you are currently running on?

**Comment by tianon** [comment]
I'm on Debian 10 (Buster), although I'm running this inside a Docker container to which I pass my `VULTR_API_KEY` environment variable (https://github.com/tianon/dockerfiles/blob/564ae5120f13f8b011e5a106267d23d79695b02f/vultr-cli/Dockerfile).

I'll update that to build from source instead and see if that helps. :+1:

**Comment by tianon** [comment]
Building from master via Go 1.12 appears to have worked fine (and I can run commands fine), although I will note the output from my master build's `vultr-cli version` is `Vultr-cli v0.1.0` where the release build I downloaded appears to be `Vultr-cli v0.0.1`. :confused:

**Comment by ddymko** [comment]
I will rebuild all of the available Go binaries on the release page for safe measure. Along with taking a look at your docker file and trying to pinpoint why the binary was failing within the container

**Comment by tianon** [comment]
Ok, this is fun -- I've adjusted my new build to build from the v0.1.0 tag instead of building straight from master (given that there are basically no real code changes in https://github.com/vultr/vultr-cli/compare/vultr:d529ad1...vultr:a504997), and it works if I build and run it inside `golang:1.12`, but if I then copy the binary to another (otherwise mostly empty) image and run it, it fails, which gave me the clue I needed to track this down.  If I add the `ca-certificates` package, it works fine, so it appears that a segfault is the failure mode when it can't verify the certificate of the Vultr API server? :sweat_smile:

**Comment by tianon** [comment]
OK, confirmed that the binary downloaded from https://github.com/vultr/vultr-cli/releases/tag/v0.1.0 works as well if I install `ca-certificates` first, although the failure mode is a little odd and the fact that it reports `Vultr-cli v0.0.1`. :sweat_smile: :heart: :+1:

**Comment by ddymko** [comment]
We will dig into the failure a bit more. However its good to know that the binaries on the release page are working fine! We will adjust the `vultr-cli version` accordingly as since the versions are not matching up.

**Comment by ddymko** [comment]
@tianon 

The segfault is caused because there are `ca-certificates` where not installed in the dockefile. Since we are making API calls over HTTPs this `ca-certificates` is required since Go does not bundle this into the binary. 

So the way you ran ` RUN apk add --no-cache ca-certificates ` in your dockerfile you could have also run `RUN apk add --no-cache curl` which would also install `ca-certificate` in the process. 

Hopefully this helps clear up the reason for the segfault.

**Comment by ddymko** [comment]
@tianon We had fixed the binaries and updated the ones on the release page. Thanks for spotting that error!
