### ISSUE TITLE
How to use with azure devops to publish files to vultr ?

### ISSUE THREAD

**Issue by giannik** [vultr/vultr-cli#275]
When using azure devops to build and deploy files is it possible to publish build files to vultr instance using the cli. 
Any examples  available on how to setup the configuration on azure ?

**Comment by optik-aper** [comment]
@giannik That's not yet something I've explored.  Can you be more specific about the build files you'd like to publish to an instance?  If you're trying to publish a OS to a new instance we support a couple different options.  Or if you're passing a script or something to the new instance we have some functionality that could accomplish that.
