### ISSUE TITLE
[BUG] - vultr-cli plans list does not work

### ISSUE THREAD

**Issue by gfa** [vultr/vultr-cli#276]
**Describe the bug**
vultr-cli plans list does not work

**To Reproduce**

```
$ vultr-cli plans list
error getting plan list : json: cannot unmarshal number 7.5 into Go struct field Plan.plans.monthly_cost of type int

$ vultr-cli version
Vultr-cli v2.5.2

```
**Expected behavior**
List of plans 

**Desktop (please complete the following information where applicable:**
 - OS: Debian GNU/Linux 11 (bullseye)

**Additional context**

I dont't have a configuration file, but I expose my API key as $VULTR_API_KEY

**Comment by optik-aper** [comment]
@gfa Thank you for the report.  It looks like old versions of vultr-cli can't handle the pricing.  Are you able to update to the latest release (v2.14.2)?
