### ISSUE TITLE
[BUG] - Composer detected issues in your platform. Your Composer dependencies require a PHP version  >

### ISSUE THREAD

**Issue by git-toni** [vultr/vultr-cli#294]
**Describe the bug**
When using the vultr-cli binary to interact with the Vultr API it seems the binary complains of my machine lacking PHP. Is everything necessary to use the cli tool packaged into the self-contained binary? Or does one have to install extra packages in the system?

Thanks!
**To Reproduce**
1. Either download the amd64 binary or build from source as described in README.
2. Correctly set the `VULTR_API_KEY`   env variable
3. Run `$ vultr-cli account`    (or any other command)
```
Error getting account information : gave up after 4 attempts, last error: "Composer detected issues in your platform:\n\nYour Composer dependencies require a PHP version \">= 8.1.0\".
```

**Expected behavior**
The account description rendered in the terminal.

**Screenshots**
![image](https://user-images.githubusercontent.com/2466887/215857522-2e20668e-27c9-4320-857a-e458cb9b8447.png)

**Desktop (please complete the following information where applicable:**
 - OS: Linux AMD64 Kernel 5.11.0
 - Language Version Go 1.18.1
 - Version 2.15.0

**Additional context**

**Comment by optik-aper** [comment]
@git-toni That looks to be a response from the API.  Are you still seeing it?

**Comment by git-toni** [comment]
That is correct @optik-aper, seems to be resolved now, thanks! :relaxed:
