### ISSUE TITLE
[Feature] - Omit the `-cli` suffix? (not the repository)

### ISSUE THREAD

**Issue by JounQin** [vultr/vultr-cli#377]
**Is your feature request related to a problem? Please describe.**

`-cli` is redundant

**Describe the solution you'd like**

Just rename

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by optik-aper** [comment]
@JounQin Thanks for the suggestion but we're not going to rename since it would cause confusion with our many projects which all follow a similar naming patter.  If you're interested, you should be able to alias the command yourself on your system.
