### ISSUE TITLE
Expose "enable firewall" option for kubernetes create command

### ISSUE THREAD

**Issue by evandeaubl** [vultr/vultr-cli#391]
**Is your feature request related to a problem? Please describe.**
`vultr-cli kubernetes create` doesn't currently expose the option to enable firewall group creation, which results in manual effort in order to enable that after a cluster is provisioned.

**Describe the solution you'd like**
Exposing the enable firewall option as a command line switch on `vultr-cli kubernetes create`, in the same way as the `--high-avail` option for turning on an HA control plane.

**Comment by optik-aper** [comment]
@evandeaubl Thanks for the request.  We'll get that added in the next release.
