### ISSUE TITLE
[BUG] - First run of vultr-cli prints warning

### ISSUE THREAD

**Issue by kpcyrd** [vultr/vultr-cli#433]
**Describe the bug**

I noticed on the first run of vultr-cli a warning is printed:

```
Error Reading in file: /home/user/.vultr-cli.yaml
```

When generating shell completions for packaging this line ends up in the shell completion script.

During this first run an empty file is created at that path, so it's only the first run.

**To Reproduce**
1. `rm ~/.vultr-cli.yaml`
2. `vultr-cli --help | head`

**Expected behavior**
No error is printed (especially not on stdout)

**Desktop (please complete the following information where applicable:**
 - OS: Arch Linux

**Comment by lucaspar** [comment]
@optik-aper regression?

```
$ vultr-cli version
Error reading in config file (/home/user/.vultr-cli.yaml) : open /home/user/.vultr-cli.yaml: no such file or directoryVultr-CLI v3.10.0
```

I have automatically generated completions, which produce invalid bash because of this message:

```bash
$ vultr-cli completion bash | head -n 4
Error reading in config file (/home/user/.vultr-cli.yaml) : open /home/user/.vultr-cli.yaml: no such file or directory# bash completion V2 for vultr-cli                            -*- shell-script -*-

__vultr-cli_debug()
{
```

Redirecting stderr (`2>/dev/null`) doesn't fix this, so it seems all output is going to stdout.
