### ISSUE TITLE
[BUG] - Error: error parsing flag 'mysql-long-query-time' for database update : trying to get int value of flag of type string

### ISSUE THREAD

**Issue by wela-elman** [vultr/vultr-cli#464]
**Describe the bug**
I'm using the docker version of cli, and I'm trying to update my mysql config. I keep getting this error. The problem is I didn't supply this flag to my command. I can't proceed because of this.

**To Reproduce**
1. Pull latest docker command
2. Execute this command, 

`docker run -e VULTR_API_KEY='API_KEY' vultr/vultr-cli:latest database update --mysql-require-primary-key datase_id`

3. See error

`Error: error parsing flag 'mysql-long-query-time' for database update : trying to get int value of flag of type string`

**Expected behavior**
No error should show about flag 'mysql-long-query-time' since I didn't supply 

**Desktop (please complete the following information where applicable:**
Docker Engine: 27.0.1
OS/Arch: linux/amd64
Docker Image: sha256:940e1bb3e2d20b58d3cb981e09d127543f748ea246b8346b4c4e4571e2d5b9a0

**Comment by optik-aper** [comment]
Thanks for the report!  I see the issue stemming from a string in the default flag value.  I will get a bug fix out today.
