### ISSUE TITLE
[Feature] - Delete without SUBID

### ISSUE THREAD

**Issue by attiqfsd** [vultr/vultr-cli#54]
Hello,

I am looking for an automated solution to cut down the Vultr billing and extend it to a couple of weeks extra.

I came across Vultr CLI and found it to be quite good for someone like me, who doesn't know much about APIs. I tried to use it for deletion of the Vultr server and I could do it fine.

But can you please tell me a way to delete the server without the SUBID?

Basically, I deploy a snapshot to a new server daily for a couple of hours, and then I forget to delete it. This ends up costing me a lot of extra money.

I was thinking about having an automated script which will detect the network transmission and when the data is no longer being transmitted, it runs the delete command for the server.

With the requirement of adding a SUBID in the delete command, I can't put the command inside a bash script. That is why I am asking if you can add deletion of server without SUBID if there is only 1 server is deployed.

**Comment by ddymko** [comment]
Hey @attiqfsd 

There is no way to delete an instance without the SUBID.

If you want to write bash scripts that will clean up running instances for you then you will need to do some work with AWK/SED. You could do something like run the `vultr-cli server list` and then parse out the SUBID and pass it into the delete command.
