### ISSUE TITLE
Error message on creating a resource is ''error deleteing".

### ISSUE THREAD

**Issue by rossigee** [vultr/vultr-cli#63]
**Describe the bug**
Error message on creating a resource is ''error deleteing".

**To Reproduce**

```
$ vultr-cli network create -c 10.111.0.0/24 -r 40 -d "Test private network"
error deleteing  network : Post https://api.vultr.com/v1/network/create: net/http: TLS handshake timeout
```
**Expected behavior**
To see an error message saying 'error creating network'.

**Comment by rossigee** [comment]
btw, it's very annoying that error messages don't add a linefeed - here's an example output from a script that creates two instances with two `vultr-cli` commands...

```
$ sh start-ik8s-nodes.sh 
error setting creating instance : Server add failed: No NETWORKID defined, but multiple private networks exist in this location.error setting creating instance : Server add failed: No NETWORKID defined, but multiple private networks exist in this location.$
```

**Comment by ddymko** [comment]
I'll create a ticket as an enhancement to improve the error responses for the cli!
