### ISSUE TITLE
[Feature] - Output format

### ISSUE THREAD

**Issue by axos88** [vultr/vultr-cli#72]
**Is your feature request related to a problem? Please describe.**
Parsing output with scripts

**Describe the solution you'd like**
An easy way to output say a csv or json document, or something that can be easily parsed programatically

**Describe alternatives you've considered**
Regexes.......

**Comment by sergerdn** [comment]
Pls also have a look  https://github.com/digitalocean/doctl:
```
Flags:
  -t, --access-token string   API V2 access token
  -u, --api-url string        Override default API endpoint
  -c, --config string         Specify a custom config file (default "$HOME/.config/doctl/config.yaml")
      --context string        Specify a custom authentication context name
  -h, --help                  help for doctl
  -o, --output string         Desired output format [text|json] (default "text")
```

**Comment by yamada95** [comment]
I do want a `--no-header` flag when listing instance,  so I can do batch operation in bash shell easier.

**Comment by Justinzobel** [comment]
I'd still love a CSV output as it's a much simpler format to work with in many scripts.

**Comment by fharper** [comment]
JSON output format would be great!

**Comment by Levilutz** [comment]
This change would be great, and would go miles towards more convenient migration to Vultr from competitors. Any movement since @relwell's [PR](https://github.com/vultr/vultr-cli/pull/292)? @optik-aper you mentioned govultr changes that superseded that PR, are those visible anywhere?

**Comment by optik-aper** [comment]
@Levilutz Sorry, somehow I missed this mention.  The changes are in [govultr](https://github.com/vultr/govultr) so yeah, we can make this a priority seeing that there is so much demand.  I'll try to get it in for the next minor release.

**Comment by chrisdeeming** [comment]
Any updates to this @optik-aper? It looks like we were very close to having this via #292 which was closed over a year ago. I'd like to transition to using the CLI but I won't be able to do that until the output can be parsed programmatically via JSON.

Many thanks!

**Comment by optik-aper** [comment]
@chrisdeeming It's my main focus at the moment and I'm almost done.  The next release will support a `--output json` flag on all commands.

**Comment by chrisdeeming** [comment]
> @chrisdeeming It's my main focus at the moment and I'm almost done.  The next release will support a `--output json` flag on all commands. 
> 
> 

Nice. Great work! Will be excited to check it out.
